version: '3.5'

services:
  backend:
      image: backend
      build: backend-example-docker
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=hunter2
        - DB_HOST=postgres
        - VIRTUAL_HOST=localtest.me
      ports:
        - 8000:8000
      volumes:
        - ${PWD}/logs.txt:/backend-example-docker/logs.txt
      container_name: backend
  
  frontend:
    image: frontend
    build: frontend-example-docker
    environment:
      - API_URL=/api
      - VIRTUAL_HOST=localtest.me
    ports:
      - 5000:5000
    container_name: frontend
  
  redis:
    image: redis
    ports:
     - 6379:6379
    volumes:
      - ./redis-data:/data
    container_name: redis
    entrypoint: redis-server --appendonly yes

  postgres:
    image: postgres
    ports: 
     - 5432:5432
    environment:
       - POSTGRES_PASSWORD=hunter2
    container_name: postgres

  proxy:
    image: jwilder/nginx-proxy
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: nginx-proxy