version: '3.5'

services:
  backend:
      # Using image created before hardcoding FRONT_URL to allow easier configuration here
      image: '1.6'
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=hunter2
        - DB_HOST=postgres
        # - REDIS_PORT=6379
      ports:
        - 8000:8000
      volumes:
        - ${PWD}/logs.txt:/backend-example-docker/logs.txt
      container_name: backend
  
  frontend:
    # Using image created before hardcoding API_URL to allow easier configuration here
    image: '1.5'
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
    container_name: frontend
  
  redis:
    image: redis
    ports:
     - 6379:6379
    volumes:
      - ./redis-data:/data
    container_name: redis
    entrypoint: redis-server --appendonly yes

  postgres:
    image: postgres
    ports: 
     - 5432:5432
    environment:
       - POSTGRES_PASSWORD=hunter2
    container_name: postgres